// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmmnrdkmcrjwgnagnidz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtbW5yZGttY3Jqd2duYWduaWR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NjExMzEsImV4cCI6MjA2MzEzNzEzMX0.QkBO-QGYWugO8m1FKdYTld4sRJuJ8SIdbHwv5ztAIU8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);